### ISSUE TITLE
Conversion error Jekyll Converters Scss encountered error while converting assets/css/styles.scss

### ISSUE THREAD

**Issue by JackieGable** [MichaelCurrin/jekyll-bootstrap-quickstart#1]
This is my first time ever submitting an issue with something on Github, so I hope I'm doing this right. If not, please forgive my ignorance. 
I followed the instructions in the Readme and the only thing I did differently was to drop the 'makefile' prefix since I'm running this on a windows pc.  Here is the error message I'm getting when I run: bundle exec jekyll serve --open-url http://localhost:4000/ --trace. 
```
Generating...
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/styles.scss':
                    Error: File to import not found or unreadable: bootstrap-5.1.0/assets/stylesheets/bootstrap. on line 6:1 of styles.scss >> @import "bootstrap-5.1.0/assets/stylesheets/bootstrap"; ^ 
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:190:in `rescue in convert': Error: File to import not found or unreadable: bootstrap-5.1.0/assets/stylesheets/bootstrap. (Jekyll::Converters::Scss::SyntaxError)
        on line 6:1 of styles.scss
>> @import "bootstrap-5.1.0/assets/stylesheets/bootstrap";
```
I also tried updating the Gemfile with this: 
```
gem 'bootstrap', '~> 5.1', '>= 5.1.3'
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
```
I tried running bundle update then running the serve command again and I'm still getting the same error message. I've also tried removing the version number on the boostrap in the Gemfile but still get the same error message. Do you have any idea what I could be doing wrong?

**Comment by MichaelCurrin** [comment]
Hmm thanks for the info, that is useful. I'll have a look.

**Comment by MichaelCurrin** [comment]
Oh I figured out the issue. It's because I made a hack to use the exact version number in the CSS to match the gem and the gem got upgraded.

https://github.com/MichaelCurrin/jekyll-bootstrap-quickstart/blob/6b9f2876ba72590da0a56dc0624a1d85da1a4c76/assets/css/styles.scss#L10

I've fixed the Gemfile to use an exact version of 5.1.3 and not a `~>` version which changes as 5.1.X

**Comment by MichaelCurrin** [comment]
Do a pull on main

Install deps

and serve

**Comment by MichaelCurrin** [comment]
Let me know if you have ideas to make it less hacky.

This did not work from [docs](https://github.com/twbs/bootstrap-rubygem)

```scss
@import "bootstrap";
```

So I must use

```scss
@import "bootstrap-5.1.3/assets/stylesheets/bootstrap";
```

**Comment by mslinn** [comment]
I found that I had to use:
```scss
@import "vendor/bundle/ruby/2.7.0/gems/bootstrap-5.1.3/assets/stylesheets/bootstrap";
```
... or `make serve` failed with:
```
bundle exec jekyll serve --trace --livereload
Configuration file: /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/_config.yml
            Source: /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart
       Destination: /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/styles.scss':
                    Error: File to import not found or unreadable: bootstrap-5.1.3/assets/stylesheets/bootstrap. on line 7:1 of styles.scss >> @import "bootstrap-5.1.3/assets/stylesheets/bootstrap"; ^
Traceback (most recent call last):
        29: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `<main>'
        28: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `load'
        27: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
        26: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        25: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        24: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        23: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        22: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        21: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        20: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        19: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
        18: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        17: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:36:in `process'
        16: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:65:in `build'
        15: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:28:in `process_site'
        14: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:80:in `process'
        13: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:211:in `render'
        12: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:538:in `render_pages'
        11: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:538:in `each'
        10: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:539:in `block in render_pages'
         9: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:547:in `render_regenerated'
         8: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:63:in `run'
         7: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:84:in `render_document'
         6: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:104:in `convert'
         5: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:104:in `reduce'
         4: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:104:in `each'
         3: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:106:in `block in convert'
         2: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:185:in `convert'
         1: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'
styles.scss:7: Error: File to import not found or unreadable: bootstrap-5.1.3/assets/stylesheets/bootstrap. (SassC::SyntaxError)
        on line 7:1 of styles.scss
>> @import "bootstrap-5.1.3/assets/stylesheets/bootstrap";

   ^
        28: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `<main>'
        27: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `load'
        26: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
        25: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        24: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        23: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        22: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        21: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        20: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        19: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        18: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
        17: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        16: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:36:in `process'
        15: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:65:in `build'
        14: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:28:in `process_site'
        13: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:80:in `process'
        12: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:211:in `render'
        11: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:538:in `render_pages'
        10: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:538:in `each'
         9: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:539:in `block in render_pages'
         8: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:547:in `render_regenerated'
         7: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:63:in `run'
         6: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:84:in `render_document'
         5: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:104:in `convert'
         4: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:104:in `reduce'
         3: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:104:in `each'
         2: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:106:in `block in convert'
         1: from /mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:182:in `convert'
/mnt/f/work/cadenzaHome/jekyll-bootstrap-quickstart/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:190:in `rescue in convert': Error: File to import not found or unreadable: bootstrap-5.1.3/assets/stylesheets/bootstrap. (Jekyll::Converters::Scss::SyntaxError)
        on line 7:1 of styles.scss
>> @import "bootstrap-5.1.3/assets/stylesheets/bootstrap";

   ^
make: *** [Makefile:19: serve] Error 1
```

Changing `load_paths` in `_config.yml` to the following was the proper fix:
```
vendor/bundle/ruby/2.7.0/gems/
```
I wonder if there is a way to abstract the version of Ruby in the YAML?

**Comment by MichaelCurrin** [comment]
The solution with `@import "bootstrap-5.1.3...` (and not starting on vendor path) worked for me and is shorter and would be prefer to keep that style.

I am using Ruby 3. and perhaps Ruby 3 will work with the short path for you too.

**Comment by MichaelCurrin** [comment]
I don't want the config to say exactly which Ruby version is used because then the repo only works on 2.7 or 3.1 or 3.2 or whatever. 

And I don't think the Ruby version can be referenced dynamically and added in the config.
