### ISSUE TITLE
Build failed on Netlify with Bootstrap Gem

### ISSUE THREAD

**Issue by SebSwan** [MichaelCurrin/jekyll-bootstrap-quickstart#2]
Hello,

I use Netlfy as hosting service. The build is done from the fetched gem
```
10:52:00 AM: Using sassc-rails 2.1.2
10:52:00 AM: Fetching bootstrap 5.1.3
10:52:00 AM: Installing bootstrap 5.1.3
10:52:00 AM: Bundle complete! 3 Gemfile dependencies, 57 gems now installed.
10:52:00 AM: Bundled gems are installed into `/opt/build/cache/bundle`
10:52:00 AM: Gem bundle installed
```
but https://github.com/import "bootstrap-5.1.3/assets/stylesheets/bootstrap" seems pointing in the wrong path, is there a solution to correct this problem ?
```
bundle exec jekyll build
10:52:02 AM: Configuration file: /opt/build/repo/_config.yml
10:52:02 AM:             Source: /opt/build/repo
10:52:02 AM:        Destination: /opt/build/repo/_site
10:52:02 AM:  Incremental build: disabled. Enable with --incremental
10:52:02 AM:       Generating...
10:52:02 AM:   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/styles.scss':
10:52:02 AM:                     Error: File to import not found or unreadable: bootstrap-5.1.3/assets/stylesheets/bootstrap. on line 7:1 of styles.scss >> @import "bootstrap-5.1.3/assets/stylesheets/bootstrap"; ^ 
10:52:02 AM:                     ------------------------------------------------
10:52:02 AM:       Jekyll 4.2.2   Please append `--trace` to the `build` command 
10:52:02 AM:                      for any additional information or backtrace. 
10:52:02 AM:                     ------------------------------------------------
```
Thanks

**Comment by SebSwan** [comment]
It seems the problem exist with Github pages too

from github page deployment

```
Fetching sassc-rails 2.1.2
Installing sassc-rails 2.1.2
Fetching bootstrap 5.1.3
Installing bootstrap 5.1.3
Bundle complete! 3 Gemfile dependencies, 57 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/styles.scss':
                    Error: File to import not found or unreadable: bootstrap-5.1.3/assets/stylesheets/bootstrap. on line 7:1 of styles.scss >> @import "bootstrap-5.1.3/assets/stylesheets/bootstrap"; ^ 
                    ------------------------------------------------
      Jekyll 4.2.2   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/usr/gem/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:200:in `rescue in sass_convert': Error: File to import not found or unreadable: bootstrap-5.1.3/assets/stylesheets/bootstrap. (Jekyll::Converters::Scss::SyntaxError)
        on line 7:1 of styles.scss
>> @import "bootstrap-5.1.3/assets/stylesheets/bootstrap";

   ^
	from /usr/gem/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:192:in `sass_convert'
	from /usr/gem/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:186:in `convert'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:106:in `block in convert'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:104:in `each'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:104:in `reduce'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:104:in `convert'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:84:in `render_document'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/renderer.rb:63:in `run'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/site.rb:547:in `render_regenerated'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/site.rb:539:in `block in render_pages'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/site.rb:538:in `each'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/site.rb:538:in `render_pages'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/site.rb:211:in `render'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/site.rb:80:in `process'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:28:in `process_site'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /usr/gem/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:29:in `load'
	from /usr/local/bundle/bin/jekyll:29:in `<main>'
styles.scss:7: Error: File to import not found or unreadable: bootstrap-5.1.3/assets/stylesheets/bootstrap. (SassC::SyntaxError)
        on line 7:1 of styles.scss
>> @import "bootstrap-5.1.3/assets/stylesheets/bootstrap";

```

**Comment by MichaelCurrin** [comment]
Hi. I investigated this issue in #1. Please see solutions there.

I updated the Gemfile to use 5.1.3 version of Bootstrap exactly to fix this issue - so make sure you have the latest code on master and also delete the Gemfile.lock and make a new one if you need it

**Comment by SebSwan** [comment]
Ok, many thanks for your response! As workaround, I ended up by copy/pasting the bootstrap library in the css folder.

I will retry with the Gem soon.
